var HeaderTemplate = {
    Menu: {
        HomeSubMenu: function () {

            var SubMenu = '<div class="tab-rb-submenu inline-block v-align-mid"> <div class="p-relative "> '
                    + '<a style="width:130px;"  href="/myalerts" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light myalerts p-relative" data-type="page" data-submenu="myalerts"> <span class="submenu-title t-caps f-color-w"> My Alerts </span> <span class="cnt-blk"> <span class="countclass">' + sessionStorage.MYALERTSCOUNT + '</span> </span> </a> <a href="/incidents" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light incidents p-relative" data-type="page" data-submenu="incidents"> <div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="margin-top:-4px;"> incidents </div></a> <a href="/policies" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light policies p-relative" data-type="page" data-submenu="policies"> <span class="submenu-title t-caps f-color-w"> Policies </span> </a> <a href="/archives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light archives p-relative" data-type="page" data-submenu="archives" style="visibility:hidden;"> <span class="submenu-title t-caps f-color-w"> Archive </span> </a> <a href="/viewarchives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light view_archives p-relative" data-type="page" data-submenu="view_archives"> <span class="submenu-title t-caps f-color-w"> View Archived </span> <span class="cnt-blk"> <span class="countclassarch"> ' + sessionStorage.ArchieveCOUNT + ' </span>  </span></a> <div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortby"> <div class="sort-text f-italic"> ' + sortText + ' </div><div class="sprite-im drop-down-icon submenu-drop-icon"> &nbsp; </div></div></div><div class="clear"> </div></div>';
        },
        DynamicHeaderTemplate: function () {
            var sortText = "";
            var subMenu = "";

            if (HOMEPAGERESPONSE.SORTBYALPHABETICALVIEW) {
                sortText = "Alphabetical";
            } else if (HOMEPAGERESPONSE.SORTBYRECENTVIEW) {
                sortText = "Recent";
            } else {
                sortText = "Recent";
            }
            if (sessionStorage.loginType == 'AgencyAdmin') {
                var MainMenu = '<a href="/home" class="snap menu-box left f-sz-18 opensans-light home p-relative f-color-w selected-tab" data-type="page" data-page="home"> <div class="menu-center"> <div class="sprite-im home-icon menu-icon">&nbsp;</div><span class="menu-text t-upper">Home</span> </div></a> <a href="/carriers" class="snap menu-box left f-sz-18 opensans-light carriers p-relative f-color-w" data-type="page" data-page="carriers"> <div class="menu-center"> <div class="sprite-im carriers-icon menu-icon" style="background-position:  0px -42px;width: 37px;height:31px;">&nbsp;</div><span class="menu-text t-upper" style="  top: -28px;">Carriers</span> </div></a> <a href="/customers" class="snap menu-box left f-sz-18 opensans-light customers p-relative f-color-w" data-type="page" data-page="customers"> <div class="menu-center"> <div class="sprite-im customers-icon menu-icon" style="background-position: -38px -42px;width: 36px;height: 29px;">&nbsp;</div><span class="menu-text t-upper" style="  top: -25px;">Customers</span> </div></a> <a href="/myreps" class="snap menu-box left f-sz-18 opensans-light myreps p-relative f-color-w" data-type="page" data-page="myreps"> <div class="menu-center"> <div class="sprite-im myreps-icon menu-icon" style="background-position: -77px -6px;width: 23px;height:28px;">&nbsp;</div><span class="menu-text t-upper" style="  top: -24px;">My Reps</span> </div></a>';

                var subMenuContent = sessionStorage.getItem("SUBMENU");

                if (subMenuContent == "HOME_PAGE") {
                    subMenu = '<div class="tab-rb-submenu inline-block v-align-mid"> <div class="p-relative "> '
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-homesubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<a style="width:150px;"  href="/myalerts" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light myalerts p-relative" data-type="page" data-submenu="myalerts"> <span class="submenu-title t-caps f-color-w"> My Alerts </span> <span class="cnt-blk">'
                            + ' <span class="countclass"> ' + sessionStorage.MYALERTSCOUNT + ' </span>  </span> </a> <a href="/incidents" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light incidents p-relative" data-type="page" data-submenu="incidents"> <div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> incidents </div></a> <a href="/policies" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light policies p-relative" data-type="page" data-submenu="policies"> <span class="submenu-title t-caps f-color-w"> Policies </span> </a> <a href="/archives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light archives p-relative" data-type="page" data-submenu="archives" style="margin-left:40px;visibility:hidden;"> <span class="submenu-title t-caps f-color-w"> Archive </span> </a> <a href="/viewarchives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light view_archives p-relative" data-type="page" data-submenu="view_archives"  style="  width: 19%;"> <span class="submenu-title t-caps f-color-w"> View Archived </span> <span class="cnt-blk">  <span class="countclassarch"> ' + sessionStorage.ArchieveCOUNT + ' </span>  </span></a> <div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortby" style="  margin-left: -10px;width: 132px;"> <div class="sort-text f-italic"> ' + sortText + ' </div><div class="sprite-im drop-down-icon submenu-drop-icon"> &nbsp; </div></div></div><div class="clear"> </div></div>';
                }
                if (subMenuContent == "CARRIER_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox snap left f-sz-16 ptsans-light carriers p-relative f-color-green" data-type="page" data-submenu="carriers"><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> carriers</span><span id="id-carrierpage-headertext"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="carriers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycarrier" style="float:right;"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div></div></div>';
                }
                if (subMenuContent == "CUSTOMER_PAGE") {//CUSTOMER_PAGE
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16  ptsans-light  customers p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid  t-upper"> customers</span><span id="id-customers-headername">  </span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="customers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative">'
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-customerssubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycustomer"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div>'

                            + '<a href="/assignrep" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light assignrep p-relative" data-type="page" data-submenu="assignrep" style="width:27%;margin-right:4px;margin-left:5px;"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;  margin-left: 0.5px;"> assign rep</div><div class="cnt-blk inline-block v-align-mid" style="display:none;"><span class=""></span></div></a><a href="/pushmessage" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light pushmessage p-relative" data-type="page" data-submenu="pushmessage" style="min-width:130px;max-width:192px;"><div class="sprite-im message-icon inline-block tab-icon v-align-mid" style="display:block;margin-left:-4px;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: 0px;"> push message</div><div class="cnt-blk inline-block v-align-mid" style="display:none;"><span class=""></span></div></a></div></div>';
                }
                if (subMenuContent == "MYREPS_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 ptsans-light myreps p-relative f-color-green" data-type="page" data-submenu="myreps"><div class=""><div class="sprite-im myreps-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text t-upper inline-block myreps v-align-mid" data-type="page" data-submenu="myreps"> my reps</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="myreps-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative">'
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-myrepssubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbyreps"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href="/invitereps" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light invitereps p-relative" data-type="page" data-submenu="invitereps" style="width:145px !important;"><div class="sprite-im invite-reps-icon inline-block tab-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> invite reps</div><div class="cnt-blk inline-block v-align-mid" style="display:none;"><span class=""></span></div></a><a href="/privacy" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light privacy p-relative" data-type="page" data-submenu="privacy"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> privacy</div><div class="cnt-blk inline-block v-align-mid" style="display:none;"><span class=""></span></div></a></div></div>';
                }
                if (subMenuContent == "CUSTOMERSVIEW_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16  ptsans-light  customers p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> customers</span><span id="id-customers-headername"> > Ramesh</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="customers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycustomer"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href="/assignrep" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light assignrep p-relative" data-type="page" data-submenu="assignrep"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;  margin-left: 0.5px;"> assign rep</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a><a href="/pushmessage" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light pushmessage p-relative" data-type="page" data-submenu="pushmessage" style="display: none;" style="max-width:192px;width:30%;"><div class="sprite-im message-icon inline-block tab-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: 0px;"> push message</div><div class="cnt-blk inline-block v-align-mid" style="display:none;"><span class=""></span></div></a></div></div>';
                }
                if (subMenuContent == "PROFILE_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 opensans-light myprofile t-upper p-relative f-color-green" data-type="page" data-submenu="myprofile"><div class=""><div class="sprite-im myprofile-icon inline-block v-align-mid mr-space-10" style="margin-top:-1px"></div><span class="sub-menu-text inline-block v-align-mid"> my profile</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="myprofile-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><a href="/edit" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light edit p-relative" data-type="page" data-submenu="edit"><div class="sprite-im inline-block edit-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid " style="  margin-top: -4px;"> edit</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
                }

            }
            else if (sessionStorage.loginType == 'AgencyRepresentative') {
                // var MainMenu = '<a href="/home" class="snap menu-box left f-sz-18 opensans-light home p-relative f-color-w selected-tab" data-type="page" data-page="home"> <div class="menu-center"> <div class="sprite-im home-icon menu-icon">&nbsp;</div><span class="menu-text t-upper">Home</span> </div></a> <a href="/carriers" class="snap menu-box left f-sz-18 opensans-light carriers p-relative f-color-w" data-type="page" data-page="carriers"> <div class="menu-center"> <div class="sprite-im carriers-icon menu-icon" style="background-position:  0px -38px;width: 37px;height:31px;">&nbsp;</div><span class="menu-text t-upper">Carriers</span> </div></a> <a href="/customers" class="snap menu-box left f-sz-18 opensans-light customers p-relative f-color-w" data-type="page" data-page="customers"> <div class="menu-center"> <div class="sprite-im customers-icon menu-icon" style="background-position: -38px -39px;width: 36px;height: 29px;">&nbsp;</div><span class="menu-text t-upper">Customers</span> </div></a> <a href="/myreps" class="snap menu-box left f-sz-18 opensans-light myreps p-relative f-color-w" data-type="page" data-page="myreps"> <div class="menu-center"> <div class="sprite-im myreps-icon menu-icon" style="background-position: -77px -4px;width: 23px;height:28px;">&nbsp;</div><span class="menu-text t-upper">My Reps</span> </div></a>';
                var MainMenu = '<a href="/home" class="snap menu-box left f-sz-18 opensans-light home p-relative f-color-w selected-tab" data-type="page" data-page="home"> <div class="menu-center"> <div class="sprite-im home-icon menu-icon">&nbsp;</div><span class="menu-text t-upper">Home</span> </div></a> <a href="/carriers" class="snap menu-box left f-sz-18 opensans-light carriers p-relative f-color-w" data-type="page" data-page="carriers"> <div class="menu-center"> <div class="sprite-im carriers-icon menu-icon" style="background-position:  0px -42px;width: 37px;height:31px;">&nbsp;</div><span class="menu-text t-upper" style="  top: -28px;">Carriers</span> </div></a> <a href="/customers" class="snap menu-box left f-sz-18 opensans-light customers p-relative f-color-w" data-type="page" data-page="customers"> <div class="menu-center"> <div class="sprite-im customers-icon menu-icon" style="background-position: -38px -42px;width: 36px;height: 29px;">&nbsp;</div><span class="menu-text t-upper" style="  top: -25px;">Customers</span> </div></a> <a href="/myreps" class="snap menu-box left f-sz-18 opensans-light myreps p-relative f-color-w" data-type="page" data-page="myreps"> <div class="menu-center"> <div class="sprite-im myreps-icon menu-icon" style="background-position: -77px -6px;width: 23px;height:28px;">&nbsp;</div><span class="menu-text t-upper" style="  top: -24px;">My Reps</span> </div></a>';
                var subMenuContent = sessionStorage.getItem("SUBMENU");

                if (subMenuContent == "HOME_PAGE") {

                    var count = sessionStorage.MYALERTSCOUNT;

                    subMenu = '<div class="tab-rb-submenu inline-block v-align-mid"> <div class="p-relative "> '
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-homesubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<a style="width:150px;"  href="/myalerts" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light myalerts p-relative" data-type="page" data-submenu="myalerts"> <span class="submenu-title t-caps f-color-w"> My Alerts </span> <span class="">'
                            + ' <span class=""> ' + count + ' </span>  </span> </a> <a href="/incidents" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light incidents p-relative" data-type="page" data-submenu="incidents"> <div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> incidents </div></a> <a href="/policies" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light policies p-relative" data-type="page" data-submenu="policies"> <span class="submenu-title t-caps f-color-w"> Policies </span> </a> <a href="/archives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light archives p-relative" data-type="page" data-submenu="archives" style="margin-left:40px;visibility:hidden;"> <span class="submenu-title t-caps f-color-w"> Archive </span> </a> <a href="/viewarchives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light view_archives p-relative" data-type="page" data-submenu="view_archives"  style="  width: 19%;"> <span class="submenu-title t-caps f-color-w"> View Archived </span> <span class="cnt-blk">  <span class="countclassarch"> ' + sessionStorage.ArchieveCOUNT + ' </span> </span></a> <div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortby" style="  margin-left: -10px;width: 132px;"> <div class="sort-text f-italic"> ' + sortText + ' </div><div class="sprite-im drop-down-icon submenu-drop-icon"> &nbsp; </div></div></div><div class="clear"> </div></div>';
                }
                if (subMenuContent == "CARRIER_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox snap left f-sz-16 ptsans-light carriers p-relative f-color-green" data-type="page" data-submenu="carriers"><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> carriers</span><span id="id-carrierpage-headertext"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="carriers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycarrier" style="float:right;"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div></div></div>';
                }
                if (subMenuContent == "CUSTOMER_PAGE") {//CUSTOMER_PAGE
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16  ptsans-light  customers p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> customers</span><span id="id-customers-headername">  </span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="customers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative">'
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-customerssubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycustomer"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div>'

                            + '<a href="/assignrep" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light assignrep p-relative" data-type="page" data-submenu="assignrep" style="display:none;width:27%;margin-right:4px;margin-left:5px;"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;  margin-left: 0.5px;"> assign rep</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a><a href="/pushmessage" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light pushmessage p-relative" data-type="page" data-submenu="pushmessage" style="display:none;min-width:130px;max-width:192px;"><div class="sprite-im message-icon inline-block tab-icon v-align-mid" style="display:block;margin-left:-4px;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: 0px;"> push message</div><div class="cnt-blk inline-block v-align-mid" style="display:none;"><span class=""></span></div></a></div></div>';
                }
                if (subMenuContent == "MYREPS_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 ptsans-light myreps p-relative f-color-green" data-type="page" data-submenu="myreps"><div class=""><div class="sprite-im myreps-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block  myreps v-align-mid snap t-upper" data-type="page" data-submenu="myreps"> my reps</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="myreps-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative">'
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-myrepssubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbyreps"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href="/invitereps" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light invitereps p-relative" data-type="page" data-submenu="invitereps" style="display:none;width:145px !important;"><div class="sprite-im invite-reps-icon inline-block tab-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> invite reps</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a><a href="/privacy" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light privacy p-relative" data-type="page" data-submenu="privacy" style="display:none;"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> privacy</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
                }
                if (subMenuContent == "CUSTOMERSVIEW_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16  ptsans-light  customers p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> customers</span><span id="id-customers-headername"> > Ramesh</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="customers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycustomer"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href="/assignrep" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light assignrep p-relative" data-type="page" data-submenu="assignrep"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;  margin-left: 0.5px;"> assign rep</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a><a href="/pushmessage" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light pushmessage p-relative" data-type="page" data-submenu="pushmessage" style="display: none;" style="max-width:192px;width:30%;"><div class="sprite-im message-icon inline-block tab-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: 0px;"> push message</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
                }
                if (subMenuContent == "PROFILE_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 opensans-light myprofile t-upper p-relative f-color-green" data-type="page" data-submenu="myprofile"><div class=""><div class="sprite-im myprofile-icon inline-block v-align-mid mr-space-10" style="margin-top:-1px"></div><span class="sub-menu-text inline-block v-align-mid"> my profile</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="myprofile-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><a href="/edit" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light edit p-relative" data-type="page" data-submenu="edit"><div class="sprite-im inline-block edit-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid " style="  margin-top: -4px;"> edit</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
                }

//                var MainMenu = '<a href="/home" class="snap menu-box left f-sz-18 opensans-light home p-relative f-color-w selected-tab" data-type="page" data-page="home"> <div class="menu-center"> <div class="sprite-im home-icon menu-icon">&nbsp;</div><span class="menu-text t-caps">Home</span> </div></a> <a href="/agency" class="snap menu-box left f-sz-18 opensans-light agencyinfo p-relative f-color-w" data-type="page" data-page="agency"> <div class="menu-center"> <div class="sprite-im carriers-icon menu-icon" style="background-position:  0px -38px;width: 37px;height:31px;">&nbsp;</div><span class="menu-text t-caps">AGENCY</span> </div></a> '
//                        + '<a href="/customers" class="snap menu-box left f-sz-18 opensans-light customers p-relative f-color-w" data-type="page" data-page="customers"> <div class="menu-center"> <div class="sprite-im customers-icon menu-icon" style="background-position: -38px -39px;width: 36px;height: 29px;">&nbsp;</div><span class="menu-text t-caps">Customers</span> </div></a> ';
//                var subMenuContent = localStorage.getItem("SUBMENU");
//
//                if (subMenuContent == "HOME_PAGE") {
//                    subMenu = '<div class="tab-rb-submenu inline-block v-align-mid"> <div class="p-relative "> '
//                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-homesubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
//                            + '<a style="width:115px;"  href="/myalerts" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light myalerts p-relative" data-type="page" data-submenu="myalerts"> <span class="submenu-title t-caps f-color-w"> My Alerts </span> <span class="cnt-blk"> ( <span class=""> ' + sessionStorage.MYALERTSCOUNT + ' </span> ) </span> </a> <a href="/incidents" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light incidents p-relative" data-type="page" data-submenu="incidents"> <div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> incidents </div></a> <a href="/policies" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light policies p-relative" data-type="page" data-submenu="policies"> <span class="submenu-title t-caps f-color-w"> Policies </span> </a> <a href="/archives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light archives p-relative" data-type="page" data-submenu="archives" style="visibility:hidden;"> <span class="submenu-title t-caps f-color-w"> Archive </span> </a> <a href="/viewarchives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light view_archives p-relative" data-type="page" data-submenu="view_archives" style="  width: 17%;"> <span class="submenu-title t-caps f-color-w"> View Archived </span><span class="cnt-blk"> ( <span class=""> ' + sessionStorage.ArchieveCOUNT + ' </span> ) </span> </a> <div id="id-sortby" href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortby"> <div class="sort-text f-italic"> ' + sortText + ' </div><div class="sprite-im drop-down-icon submenu-drop-icon"> &nbsp; </div></div></div><div class="clear"> </div></div>';
//                }
//                if (subMenuContent == "AGENCY_PAGE") {
//                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox left f-sz-16 opensans-light carriers t-upper p-relative f-color-green" data-type="page" data-submenu="carriers"><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 "> </div><span class="sub-menu-text inline-block v-align-mid"> AGENCY</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="carriers-customer" style="display:none;"></a></div>';
//                }
//                if (subMenuContent == "CUSTOMER_PAGE") {
//                    subMenu = '<div class=\"mb-submenu-in p-relative\"> <div class=\"bcrum-lb-submenu clr-fl inline-block v-align-mid\"><a href=\"#\" class=\"carrier-headerbox snap left f-sz-16  ptsans-light  customers t-upper p-relative f-color-green\" data-type=\"page\" data-submenu=\"customers\"><div class=\"\"><div class=\"sprite-im customers-icon inline-block v-align-mid mr-space-10 \">&nbsp;</div><span class=\"sub-menu-text inline-block v-align-mid\"> customers </span><span id=\"id-carrierpage-headertext\"></span></div></a><div class=\"bcrum-icon-blk left f-color-green f-sz-16 opensans-light\" style=\"display:none;\">&gt;</div><a href=\"#\" class=\"snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green\" data-type=\"page\" data-submenu=\"carriers-customer\" style=\"display:none;\"></a></div><div class=\"tab-rb-submenu inline-block v-align-mid\" style=\"width:53%;\"><div class=\"tab-rb-submenu-in-block p-relative\"><div href=\"#\" class=\"snap submenu-sort right f-sz-16 opensans-light p-relative\" data-type=\"page\" data-submenu=\"sortbycustomer\"><div class=\"sort-text f-italic\">' + sortText + '</div><div class=\"sprite-im drop-down-icon submenu-drop-icon\">&nbsp;</div></div></div></div></div>';
//                }
//                if (subMenuContent == "CUSTOMERSVIEW_PAGE") {
//                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox left f-sz-16 opensans-light snap carriers t-upper p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 "> </div><span class="sub-menu-text inline-block v-align-mid"> CUSTOMERS </span><span id="id-carrierpage-headertext">&gt; Suresh</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="carriers-customer" style="display:none;"></a></div>';
//                }
//                if (subMenuContent == "PROFILE_PAGE") {
//                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 opensans-light myprofile t-upper p-relative f-color-green" data-type="page" data-submenu="myprofile"><div class=""><div class="sprite-im inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid"> my profile</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="myprofile-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><a href="/edit" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light edit p-relative" data-type="page" data-submenu="edit"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid " style="  margin-top: -4px;"> edit</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
//                }
            } else if (sessionStorage.loginType == 'CarrierAdmin') {

                var MainMenu = '<div class="mb-menu bg-color-green clr-fl t-center t-upper"> <a href="/home" class="snap menu-box left f-sz-18 opensans-light home p-relative f-color-w selected-tab" data-type="page" data-page="home"> <div class="menu-center"> <div class="sprite-im home-icon menu-icon">&nbsp;</div><span class="menu-text t-caps">HOME</span> </div></a> '
                        + '<a href="/Agencies" class="snap menu-box left f-sz-18 opensans-light CarrierAgencies p-relative f-color-w" data-type="page" data-page="carrieragency"> <div class="menu-center"> <div class="sprite-im carriers-icon menu-icon" style="background-position:  0px -38px;width: 37px;height:31px;">&nbsp;</div><span class="menu-text t-caps">AGENCIES</span> </div></a>'
                        + '<a href="/customers" class="snap menu-box left f-sz-18 opensans-light customers p-relative f-color-w" data-type="page" data-page="customers"> <div class="menu-center"> <div class="sprite-im customers-icon menu-icon" style="background-position: -38px -39px;width: 36px;height: 29px;">&nbsp;</div><span class="menu-text t-caps">CUSTOMERS</span> </div></a> <a href="/myreps" class="snap menu-box left f-sz-18 opensans-light carrierreps p-relative f-color-w" data-type="page" data-page="carrierreps"> <div class="menu-center"> <div class="sprite-im myreps-icon menu-icon" style="background-position: -77px -4px;width: 23px;height:28px;">&nbsp;</div><span class="menu-text t-caps">MY REPS</span> </div></a></div>';
                var subMenuContent = sessionStorage.getItem("SUBMENU");

                if (subMenuContent == "HOME_PAGE") {

                    subMenu = '<div class="tab-rb-submenu inline-block v-align-mid"> <div class="p-relative "> '
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-homesubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<a style="width:150px;"  href="/myalerts" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light myalerts p-relative" data-type="page" data-submenu="myalerts"> <span class="submenu-title t-caps f-color-w"> My Alerts </span> <span class="cnt-blk">'
                            + ' <span class="countclass"> ' + sessionStorage.MYALERTSCOUNT + ' </span>  </span> </a> <a href="/incidents" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light incidents p-relative" data-type="page" data-submenu="incidents"  style="  opacity: 0;pointer-events: none;"> <div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> incidents </div></a> <a href="/policies" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light policies p-relative" data-type="page" data-submenu="policies" style="  opacity: 0;pointer-events: none;"> <span class="submenu-title t-caps f-color-w"> Policies </span> </a> <a href="/archives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light archives p-relative" data-type="page" data-submenu="archives" style="margin-left:40px;visibility:hidden;"> <span class="submenu-title t-caps f-color-w"> Archive </span> </a> <a href="/viewarchives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light view_archives p-relative" data-type="page" data-submenu="view_archives"  style="  width: 19%;margin-left:-5px;"> <span class="submenu-title t-caps f-color-w"> View Archived </span> <span class="cnt-blk">  <span class="countclassarch"> ' + sessionStorage.ArchieveCOUNT + ' </span> </span></a> <div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortby" style="  margin-left: -10px;width: 132px;"> <div class="sort-text f-italic"> ' + sortText + ' </div><div class="sprite-im drop-down-icon submenu-drop-icon"> &nbsp; </div></div></div><div class="clear"> </div></div>';
                    //                    subMenu = '<div class="tab-rb-submenu inline-block v-align-mid"> <div class="p-relative "> '
//                            + '<div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortby"> '
//                            + '<div class="sort-text f-italic"> ' + sortText + ' </div>'
//                            + '<div class="sprite-im drop-down-icon submenu-drop-icon"> &nbsp; </div></div>'
//                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-homesubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
//                            + '<a href="/viewarchives" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light view_archives p-relative" data-type="page" data-submenu="view_archives"> <span class="submenu-title t-caps f-color-w"> View Archived </span> <span class="cnt-blk"> ( <span class="countclassarch"> ' + sessionStorage.ArchieveCOUNT + ' </span> ) </span></a> <a href="/archives" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light archives p-relative" data-type="page" data-submenu="archives" style="visibility:hidden;"> <span class="submenu-title t-caps f-color-w"> Archive </span> </a> '
//                            + '<a href=\"#\" class=\"snap left f-sz-16 opensans-light home t-upper p-relative f-color-green\" data-type=\"page\" data-submenu=\"home\"><div class=\"carrierfeeds\">'
//                            + '<div class=\"sprite-im customers-icon inline-block v-align-mid mr-space-10 \" style="background-position: 0px 0px; width: 33px;height:31px;">&nbsp;</div><span class=\"sub-menu-text inline-block v-align-mid\"> FEEDS'
//                            + ' </span><span id=\"id-customers-headername\"> </span></div></a></div><div class="clear"> </div></div>';
                }
                if (subMenuContent == "CARRIERS_AGENCY_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid">'
                            + '<a href="#" class="carrier-headerbox snap left f-sz-16 ptsans-light CarrierAgencies p-relative f-color-green" data-type="page" '
                            + 'data-submenu="carrieragency"><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid">AGENCIES</span><span id="id-carrierpage-headertext"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="carriers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbyAgencies"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div></div></div>';
                }
                if (subMenuContent == "CUSTOMER_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16  ptsans-light  customers p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> customers</span><span id="id-customers-headername">  </span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="customers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative">'
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-customerssubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycustomer"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href="/assignrep" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light assignrep p-relative" data-type="page" data-submenu="assignrep" style="width:27%;margin-left:5px;margin-right:4px;"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;  margin-left: 0.5px;"> assign rep</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a><a href="/pushmessage" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light pushmessage p-relative" data-type="page" data-submenu="pushmessage" style="max-width:198px;width:28%;"><div class="sprite-im message-icon inline-block tab-icon v-align-mid" style="display:block;margin-left:-4px;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="margin-top:0px;"> push message</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
                }
                if (subMenuContent == "CARRIER_REPS_PAGE" || subMenuContent == "MYREPS_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 ptsans-light carrierreps p-relative f-color-green" data-type="page" data-submenu="carrierreps"><div class=""><div class="sprite-im myreps-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> my reps</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="myreps-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative">'
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-myrepssubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbyreps"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href="/invitereps" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light invitereps p-relative" data-type="page" data-submenu="invitereps" style="width:145px !important;"><div class="sprite-im invite-reps-icon inline-block tab-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> invite reps</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a><a href="/privacy" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light privacy p-relative" data-type="page" data-submenu="privacy"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> privacy</div><div class="cnt-blk inline-block v-align-mid" style="display:none;"><span class=""></span></div></a></div></div>';
                }

                if (subMenuContent == "PROFILE_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 opensans-light myprofile t-upper p-relative f-color-green" data-type="page" data-submenu="myprofile"><div class=""><div class="sprite-im inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid"> my profile</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="myprofile-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative">'
                            + '<a href="/edit" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light edit p-relative" data-type="page" data-submenu="edit"><div class="sprite-im inline-block edit-icon v-align-mid" style=\"display:inline-block;margin-left:0px;margin-right: 5px;\">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid " style="  margin-top: -4px;"> edit</div><div class="cnt-blk inline-block v-align-mid" style="display:none;  float: left;  margin-right: 10px;  margin-top: 10px">(<span class=""></span>)</div></a></div></div>';
                }


            } else if (sessionStorage.loginType == 'CarrierRepresentative') {
                var MainMenu = '<div class="mb-menu bg-color-green clr-fl t-center t-upper"> <a href="/home" class="snap menu-box left f-sz-18 opensans-light home p-relative f-color-w selected-tab" data-type="page" data-page="home"> <div class="menu-center"> <div class="sprite-im home-icon menu-icon">&nbsp;</div><span class="menu-text t-caps">HOME</span> </div></a> '
                        + '<a href="/Agencies" class="snap menu-box left f-sz-18 opensans-light CarrierAgencies p-relative f-color-w" data-type="page" data-page="carrieragency"> <div class="menu-center"> <div class="sprite-im carriers-icon menu-icon" style="background-position:  0px -38px;width: 37px;height:31px;">&nbsp;</div><span class="menu-text t-caps">AGENCIES</span> </div></a>'
                        + '<a href="/customers" class="snap menu-box left f-sz-18 opensans-light customers p-relative f-color-w" data-type="page" data-page="customers"> <div class="menu-center"> <div class="sprite-im customers-icon menu-icon" style="background-position: -38px -39px;width: 36px;height: 29px;">&nbsp;</div><span class="menu-text t-caps">CUSTOMERS</span> </div></a> <a href="/myreps" class="snap menu-box left f-sz-18 opensans-light carrierreps p-relative f-color-w" data-type="page" data-page="carrierreps"> <div class="menu-center"> <div class="sprite-im myreps-icon menu-icon" style="background-position: -77px -4px;width: 23px;height:28px;">&nbsp;</div><span class="menu-text t-caps">MY REPS</span> </div></a></div>';
                var subMenuContent = sessionStorage.getItem("SUBMENU");

                if (subMenuContent == "HOME_PAGE") {
                    subMenu = '<div class="tab-rb-submenu inline-block v-align-mid"> <div class="p-relative "> '
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-homesubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<a style="width:150px;"  href="/myalerts" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light myalerts p-relative" data-type="page" data-submenu="myalerts"> <span class="submenu-title t-caps f-color-w"> My Alerts </span> <span class="cnt-blk">'
                            + ' <span class="countclass"> ' + sessionStorage.MYALERTSCOUNT + ' </span>  </span> </a> <a href="/incidents" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light incidents p-relative" data-type="page" data-submenu="incidents"  style="  opacity: 0;pointer-events: none;"> <div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> incidents </div></a> <a href="/policies" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light policies p-relative" data-type="page" data-submenu="policies" style="  opacity: 0;pointer-events: none;"> <span class="submenu-title t-caps f-color-w"> Policies </span> </a> <a href="/archives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light archives p-relative" data-type="page" data-submenu="archives" style="margin-left:40px;visibility:hidden;"> <span class="submenu-title t-caps f-color-w"> Archive </span> </a> <a href="/viewarchives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light view_archives p-relative" data-type="page" data-submenu="view_archives"  style="  width: 19%;margin-left:-5px;"> <span class="submenu-title t-caps f-color-w"> View Archived </span> <span class="cnt-blk">  <span class="countclassarch"> ' + sessionStorage.ArchieveCOUNT + ' </span>  </span></a> <div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortby" style="  margin-left: -10px;width: 132px;"> <div class="sort-text f-italic"> ' + sortText + ' </div><div class="sprite-im drop-down-icon submenu-drop-icon"> &nbsp; </div></div></div><div class="clear"> </div></div>';
//                    subMenu = '<div class="tab-rb-submenu inline-block v-align-mid"> <div class="p-relative "> '
//                            + '<div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortby"> '
//                            + '<div class="sort-text f-italic"> ' + sortText + ' </div>'
//                            + '<div class="sprite-im drop-down-icon submenu-drop-icon"> &nbsp; </div></div>'
//                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-homesubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
//                            + '<a href="/viewarchives" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light view_archives p-relative" data-type="page" data-submenu="view_archives"> <span class="submenu-title t-caps f-color-w"> View Archived </span> <span class="cnt-blk"> ( <span class="countclassarch"> ' + sessionStorage.ArchieveCOUNT + ' </span> ) </span></a> <a href="/archives" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light archives p-relative" data-type="page" data-submenu="archives" style="visibility:hidden;"> <span class="submenu-title t-caps f-color-w"> Archive </span> </a> '
//                            + '<a href=\"#\" class=\"snap left f-sz-16 opensans-light home t-upper p-relative f-color-green\" data-type=\"page\" data-submenu=\"home\"><div class=\"carrierfeeds\">'
//                            + '<div class=\"sprite-im customers-icon inline-block v-align-mid mr-space-10 \" style="background-position: 0px 0px; width: 33px;height:31px;">&nbsp;</div><span class=\"sub-menu-text inline-block v-align-mid\"> FEEDS'
//                            + ' </span><span id=\"id-customers-headername\"> </span></div></a></div><div class="clear"> </div></div>';
                }
                if (subMenuContent == "CARRIERS_AGENCY_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid">'
                            + '<a href="#" class="carrier-headerbox snap left f-sz-16 ptsans-light CarrierAgencies p-relative f-color-green" data-type="page" '
                            + 'data-submenu="carrieragency"><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid">AGENCIES</span><span id="id-carrierpage-headertext"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="carriers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbyAgencies"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div></div></div>';
                }
                if (subMenuContent == "CUSTOMER_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16  ptsans-light  customers p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> customers</span><span id="id-customers-headername">  </span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="customers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative">'
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-customerssubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycustomer"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href="/assignrep" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light assignrep p-relative" data-type="page" data-submenu="assignrep" style="display:none"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;  margin-left: 0.5px;"> assign rep</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a><a href="/pushmessage" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light pushmessage p-relative" data-type="page" data-submenu="pushmessage" style="display:none;max-width:198px;width:30%;"><div class="sprite-im message-icon inline-block tab-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="margin-top:0px;"> push message</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
                }
                if (subMenuContent == "CARRIER_REPS_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 ptsans-light carrierreps p-relative f-color-green" data-type="page" data-submenu="carrierreps"><div class=""><div class="sprite-im myreps-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> my reps</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="myreps-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative">'
                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-myrepssubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
                            + '<div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbyreps"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href="/invitereps" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light invitereps p-relative" data-type="page" data-submenu="invitereps" style="display:none;width:145px !important;"><div class="sprite-im invite-reps-icon inline-block tab-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  display:none;margin-top: -4px;"> invite reps</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
                }

                if (subMenuContent == "PROFILE_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 opensans-light myprofile t-upper p-relative f-color-green" data-type="page" data-submenu="myprofile"><div class=""><div class="sprite-im inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid"> my profile</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="myprofile-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative">'
                            + '<a href="/edit" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light edit p-relative" data-type="page" data-submenu="edit"><div class="sprite-im inline-block edit-icon v-align-mid" style=\"display:inline-block;margin-left:0px;margin-right: 5px;\">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid " style="  margin-top: -4px;"> edit</div><div class="cnt-blk inline-block v-align-mid" style="display:none;  float: left;  margin-right: 10px;  margin-top: 10px">(<span class=""></span>)</div></a></div></div>';
                }


//                var MainMenu = '<a href="/home" class="snap menu-box left f-sz-18 opensans-light home p-relative f-color-w selected-tab" data-type="page" data-page="home"> <div class="menu-center"> <div class="sprite-im home-icon menu-icon">&nbsp;</div><span class="menu-text t-caps">Home</span> </div></a> <a href="/carriers" class="snap menu-box left f-sz-18 opensans-light carriers p-relative f-color-w" data-type="page" data-page="carriers"> <div class="menu-center"> <div class="sprite-im carriers-icon menu-icon" style="background-position:  0px -38px;width: 37px;height:31px;">&nbsp;</div><span class="menu-text t-caps">Carriers</span> </div></a>'
//                        + '<a href="/agencies" class="snap menu-box left f-sz-18 opensans-light agencies-info p-relative f-color-w" data-type="page" data-page="agencies"> <div class="menu-center"> <div class="sprite-im customers-icon menu-icon" style="background-position: 0px -39px; width: 39px;height:31px;">&nbsp;</div><span class="menu-text t-caps">AGENCIES</span> </div></a> <a href="/customers" class="snap menu-box left f-sz-18 opensans-light customers p-relative f-color-w" data-type="page" data-page="customers"> <div class="menu-center"> <div class="sprite-im customers-icon menu-icon" style="background-position: -38px -39px;width: 36px;height: 29px;">&nbsp;</div><span class="menu-text t-caps">Customers</span> </div></a>';
//
//                var subMenuContent = localStorage.getItem("SUBMENU");
//
//                if (subMenuContent == "HOME_PAGE") {
//                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 opensans-light home t-upper p-relative f-color-green" data-type="page" data-submenu="home"><div class="carrierfeeds"><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 " style="background-position: 0px 0px; width: 33px;height:33px;">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid"> FEEDS </span><span id="id-customers-headername"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="customers-customer" style="display:none;"></a></div><div id="tab-rb-submenu-carrierrep" class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu=""><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div>'
//                            + '<div style="display:none;width:130px;margin-right: -79px;margin-top: 7px;height:30px;"  href="/submenus" class="snap  left f-sz-16 opensans-light homesubmenu p-relative " data-type="page" data-submenu="dt-homesubmenu"><span class="submenu-title t-caps f-color-w" style="  color: transparent;">dfgdfgddfgdfg</span></div>'
//                            + '<a href="/archives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light archives p-relative" data-type="page" data-submenu="archives" style="float:right;visibility:hidden;"> <span class="submenu-title t-caps f-color-w"> Archive </span> </a> <a href="/viewarchives" class="snap submenu-tab bg-color-green left f-sz-16 opensans-light view_archives p-relative" data-type="page" data-submenu="view_archives" style="display:none;"> <span class="submenu-title t-caps f-color-w"> View Archived </span><span class="cnt-blk"> ( <span class=""> ' + sessionStorage.ArchieveCOUNT + ' </span> ) </span> </a></div></div>';
//                }
//                if (subMenuContent == "CARRIER_PAGE") {
//                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox snap left f-sz-16 opensans-light carriers t-upper p-relative f-color-green" data-type="page" data-submenu="carriers"><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid"> carriers</span><span id="id-carrierpage-headertext"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="carriers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycarrier"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div></div></div>';
//                }
//                if (subMenuContent == "CUSTOMER_PAGE") {
//                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox snap left f-sz-16  ptsans-light  customers t-upper p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid">CUSTOMERS</span><span id="id-carrierpage-headertext"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="carriers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycustomer"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div></div></div>';
//                }
//                if (subMenuContent == "CUSTOMERSVIEW_PAGE") {
//                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox left f-sz-16 opensans-light snap carriers t-upper p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 "> </div><span class="sub-menu-text inline-block v-align-mid"> CUSTOMERS </span><span id="id-carrierpage-headertext">&gt; Suresh</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu= style="display:none;"></a></div>';
//                }
//                if (subMenuContent == "AGENCIESVIEW_PAGE") {
//                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox left f-sz-16 opensans-light snap carriers t-upper p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 "> </div><span class="sub-menu-text inline-block v-align-mid"> CUSTOMERS </span><span id="id-carrierpage-headertext">&gt; Suresh</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu= style="display:none;"></a></div>';
//                }
//                if (subMenuContent == "AGENICES_PAGE") {
//                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox snap left f-sz-16 opensans-light agencies-info t-upper p-relative f-color-green" data-type="page" data-submenu="agencies"><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid">AGENICES</span><span id="id-carrierpage-headertext"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu= style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbyAgencies"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div></div></div>';
//                }
//
//                if (subMenuContent == "PROFILE_PAGE") {
//                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 opensans-light myprofile t-upper p-relative f-color-green" data-type="page" data-submenu="myprofile"><div class=""><div class="sprite-im inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid"> my profile</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="myprofile-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><a href="/edit" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light edit p-relative" data-type="page" data-submenu="edit"><div class="sprite-im inline-block edit-icon v-align-mid" style=\"display:inline-block;margin-left:0px;margin-right: 5px;\">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid " style="  margin-top: -4px;"> edit</div></a></div></div>';
//                }
            } else {
                var MainMenu = '<a href="/home" class="snap menu-box left f-sz-18 opensans-light home p-relative f-color-w selected-tab" data-type="page" data-page="home"> <div class="menu-center"> <div class="sprite-im home-icon menu-icon">&nbsp;</div><span class="menu-text t-caps">Home</span> </div></a> <a href="/carriers" class="snap menu-box left f-sz-18 opensans-light carriers p-relative f-color-w" data-type="page" data-page="carriers" style="  margin-top: -4px;  min-height: 100px;"> <div class="menu-center"> <div class="sprite-im carriers-icon menu-icon" style="background-position:  0px -38px;width: 37px;height:31px;">&nbsp;</div><span class="menu-text t-caps"  style="  top: -25px;">Carriers</span> </div></a> <a href="/customers" class="snap menu-box left f-sz-18 opensans-light customers p-relative f-color-w" data-type="page" data-page="customers" style="display:none;"> <div class="menu-center"> <div class="sprite-im customers-icon menu-icon" style="background-position: -38px -39px;width: 36px;height: 29px;">&nbsp;</div><span class="menu-text t-caps">Customers</span> </div></a> <a href="/myreps" class="snap menu-box left f-sz-18 opensans-light agencies-info p-relative f-color-w" data-type="page" data-page="agencies"  style="  margin-top: -2px;  min-height: 100px;"> <div class="menu-center"> <div class="sprite-im myreps-icon menu-icon" style="background-position: -77px -4px;width: 23px;height:28px;">&nbsp;</div><span class="menu-text t-caps"  style="  top: -25px;">Agencies</span> </div></a>';
                var subMenu = "";
            }

            if (sessionStorage.loginType == "SuperAdmin") {
                var Header = "";
                var subMenuContent = sessionStorage.getItem("SUBMENU");

                if (subMenuContent == "HOME_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox snap left f-sz-16 ptsans-light home t-upper p-relative f-color-green" data-type="page" data-submenu="home"><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid"> home</span><span id="id-carrierpage-headertext"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="carriers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortby"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div></div></div>';
                }
                if (subMenuContent == "CARRIER_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox snap left f-sz-16 ptsans-light carriers p-relative f-color-green" data-type="page" data-submenu="carriers"><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> carriers</span><span id="id-carrierpage-headertext"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="carriers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycarrier" ><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href="/invitereps" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light invitereps p-relative" data-type="page" data-submenu="invitereps" style="width:145px !important;display:none;"><div class="sprite-im invite-reps-icon inline-block tab-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;"> invite Carriers</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
                }
                if (subMenuContent == "CUSTOMER_PAGE") {//CUSTOMER_PAGE
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid" style="width:25%;"><a href="#" class="snap left f-sz-16  ptsans-light  customers p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> customers</span><span id="id-customers-headername"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="customers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:75%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycustomer"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href="/assignrep" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light assignrep p-relative" data-type="page" data-submenu="assignrep" style="display:none;"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;  margin-left: 0.5px;"> assign rep</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a>'
                            + '<a href="/pushmessage" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light pushmessage p-relative" data-type="page" data-submenu="pushmessage" style="max-width:192px;width:30%;"><div class="sprite-im message-icon inline-block tab-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="margin-top:0px;"> push message</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a>'
                            + '<a  href="/invitereps" style="width:145px;display:none;" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light invitereps p-relative" data-type="page" data-submenu="invitereps" style="width:145px !important;"><div class="sprite-im invite-reps-icon inline-block tab-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="margin-top:-4px;"> invite Customers</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
                }
                if (subMenuContent == "CUSTOMERSVIEW_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16  ptsans-light  customers p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid t-upper"> customers</span><span id="id-customers-headername">&gt; Ramesh</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="customers-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;margin-right:5px;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbycustomer"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href="/assignrep" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light assignrep p-relative" data-type="page" data-submenu="assignrep"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: -4px;  margin-left: 0.5px;"> assign rep</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a><a href="/pushmessage" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light pushmessage p-relative" data-type="page" data-submenu="pushmessage" style="display: none;" style="max-width:192px;width:30%;"><div class="sprite-im message-icon inline-block tab-icon v-align-mid" style="display:block;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid" style="  margin-top: 0px;"> push message</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
                }
                if (subMenuContent == "PROFILE_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="snap left f-sz-16 opensans-light myprofile t-upper p-relative f-color-green" data-type="page" data-submenu="myprofile"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid"> my profile</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu="myprofile-customer" style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><a href="/edit" class="snap submenu-tab bg-color-green right f-sz-16 opensans-light edit p-relative" data-type="page" data-submenu="edit"><div class="sprite-im inline-block tab-icon v-align-mid" style="display:none;">&nbsp;</div><div class="submenu-title t-caps inline-block f-color-w v-align-mid " style="  margin-top: -4px;"> edit</div><div class="cnt-blk inline-block v-align-mid" style="display:none;">(<span class=""></span>)</div></a></div></div>';
                }
                if (subMenuContent == "CUSTOMERSVIEW_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox left f-sz-16 ptsans-light snap carriers p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im customers-icon inline-block v-align-mid mr-space-10 "> </div><span class="sub-menu-text inline-block v-align-mid"> CUSTOMERS </span><span id="id-carrierpage-headertext">&gt; Suresh</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu= style="display:none;"></a></div>';
                }
                if (subMenuContent == "AGENCIESVIEW_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox left f-sz-16 ptsans-light snap carriers p-relative f-color-green" data-type="page" data-submenu="customers"><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 "> </div><span class="sub-menu-text inline-block v-align-mid"> CUSTOMERS </span><span id="id-carrierpage-headertext">&gt; Suresh</span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu= style="display:none;"></a></div>';
                }
                if (subMenuContent == "AGENICES_PAGE") {
                    subMenu = '<div class="bcrum-lb-submenu clr-fl inline-block v-align-mid"><a href="#" class="carrier-headerbox snap left f-sz-16 ptsans-light agencies-info p-relative f-color-green" data-type="page" data-submenu="agencies" ><div class=""><div class="sprite-im carriers-icon inline-block v-align-mid mr-space-10 ">&nbsp;</div><span class="sub-menu-text inline-block v-align-mid">AGENICES</span><span id="id-carrierpage-headertext"></span></div></a><div class="bcrum-icon-blk left f-color-green f-sz-16 opensans-light" style="display:none;">&gt;</div><a href="#" class="snap left f-sz-16 opensans-light feeds-customer t-caps p-relative f-color-green" data-type="page" data-submenu= style="display:none;"></a></div><div class="tab-rb-submenu inline-block v-align-mid" style="width:53%;"><div class="tab-rb-submenu-in-block p-relative"><div href="#" class="snap submenu-sort right f-sz-16 opensans-light p-relative" data-type="page" data-submenu="sortbyAgencies"><div class="sort-text f-italic">' + sortText + '</div><div class="sprite-im drop-down-icon submenu-drop-icon">&nbsp;</div></div><a href=\"/invitereps\" class=\"snap submenu-tab bg-color-green right f-sz-16 opensans-light invitereps p-relative\" data-type=\"page\" data-submenu=\"invitereps\" style="width:150px;display:none;"><div class=\"sprite-im invite-reps-icon inline-block tab-icon v-align-mid\" style=\"display:block;\">&nbsp;</div><div class=\"submenu-title t-caps inline-block f-color-w v-align-mid\" style="margin-top:-4px;"> invite Agencies</div><div class=\"cnt-blk inline-block v-align-mid\" style=\"display:none;\">(<span class=\"cnt-no\"></span>)</div></a></div></div>';
                }
                sessionStorage.superAdminLogo = "http://icons.iconarchive.com/icons/iconshock/super-vista-general/256/administrator-icon.png";

                Header = '<div class="m-width">  <header class="w-pad"> <div class="logo-info-blk clr-fl p-relative"> <div class="lf-block left clr-fl header-left-panel"> <div class="leftblk-spacing"> <div style="width:100%;"> <div class="logo-container left"> <div class="logo-holder"> <img src="images/Logo.png" alt="" class="logo"/> </div></div><div class="left search-blk"> <form name="globalSearch" method="GET" action="#search" class="" onsubmit="event.preventDefault();"> <div style="width:100%;"> <div class="searchbox-border"> <input id="searchUserDetails" class="search-ip opensans-regular" type="search" name="" placeholder="Search"> </div></div></form> </div><div class="clear"> </div></div></div></div><div class="rg-block left p-relative"> <a href="/profile" id="profile" class="logged-user-info clr-fl snap" data-type="profile-link"> <div id="" class="left user-pic-box"> <img src="' + sessionStorage.profilePic + '" alt="Profile pic" class="setProfilePic"> </div><div class="left user-info"> <div class="opensans-regular text-ellipsis"> <span> Hi, </span> <span class="t-caps" id="profileUserName"> ' + sessionStorage.userFirstName + ' </span> </div></div><div class="left sprite-im drop-down-icon user-drop-icon"> &nbsp; </div><div class="clear"> </div></a> </div></div></header> <div> <div id="searchBarDiv" style="z-index: 99999; overflow: auto;max-height: 300px; border: 1px solid rgb(185, 184, 184); background: rgb(233, 239, 240);display:none;"> <ul id="searchResultUL" style="padding:0;margin:0;list-style:none;"> </ul> </div></div><div class="m-block p-relative"> <div class="clr-fl"> <div class="lf-block left"> <div class="leftblk-spacing"> <div class="mb-menu bg-color-green clr-fl t-center t-upper"> ' + MainMenu + ' </div><div class="mb-submenu"> <div class="mb-submenu-in p-relative"> ' + subMenu + ' </div></div></div></div><div class="rg-block left p-relative"> <div class="agency-info p-relative clr-fl bg-color-dblue"> <a class="agency-details clr-fl snap" data-type="agency-link"> <div id="" class="left agency-pic-box p-relative">'
                        + '<img src="' + sessionStorage.superAdminLogo + '" alt="Super Admin Pic" class="setAgencyPic"></div><div class="left agency-name-details t-left anim"> <div class="opensans-regular text-ellipsis f-italic f-sz-17 agency-name t-caps"> Super Admin</div><div id="adminEmailIDValue" class="opensans-regular text-ellipsis f-italic agency-email" title=' + sessionStorage.superAdminEmailId + '> ' + sessionStorage.superAdminEmailId + ' </div></div></a> </div></div></div></div><div class="topContainer"></div>'
            } else {
                Header = '<div class="m-width">  <header class="w-pad"> <div class="logo-info-blk clr-fl p-relative"> <div class="lf-block left clr-fl header-left-panel"> <div class="leftblk-spacing"> <div style="width:100%;"> <div class="logo-container left"> <div class="logo-holder"> <img src="images/Logo.png" alt="" class="logo"/> </div></div><div class="left search-blk"> <form name="globalSearch" method="GET" action="#search" class="" onsubmit="event.preventDefault();"> <div style="width:100%;"> <div class="searchbox-border"> <input id="searchUserDetails" class="search-ip opensans-regular" type="search" name="" placeholder="Search"> </div></div></form> </div><div class="clear"> </div></div></div></div><div class="rg-block left p-relative"> <a href="/profile" id="profile" class="logged-user-info clr-fl snap" data-type="profile-link"> <div id="" class="left user-pic-box"> <img src="' + sessionStorage.profilePic + '" alt="Profile pic" class="setProfilePic"> </div><div class="left user-info"> <div class="opensans-regular text-ellipsis"> <span> Hi, </span> <span class="t-caps" id="profileUserName"> ' + sessionStorage.userFirstName + ' </span> </div></div><div class="left sprite-im drop-down-icon user-drop-icon"> &nbsp; </div><div class="clear"> </div></a> </div></div></header> <div> <div id="searchBarDiv" style="z-index: 99999; overflow: auto;max-height: 300px; border: 1px solid rgb(185, 184, 184); background: rgb(233, 239, 240);display:none;"> <ul id="searchResultUL" style="padding:0;margin:0;list-style:none;"> </ul> </div></div><div class="m-block p-relative"> <div class="clr-fl"> <div class="lf-block left"> <div class="leftblk-spacing"> <div class="mb-menu bg-color-green clr-fl t-center t-upper"> ' + MainMenu + ' </div><div class="mb-submenu"> <div class="mb-submenu-in p-relative"> ' + subMenu + ' </div></div></div></div><div class="rg-block left p-relative"> <div class="agency-info p-relative clr-fl bg-color-dblue"> <a class="agency-details clr-fl snap" data-type="agency-link"> <div id="" class="left agency-pic-box p-relative">'
                        + '<img src="' + sessionStorage.agencyLogo + '" alt="agency pic" class="setAgencyPic"> <div class="edit-cover-pic p-absolute anim-opacity"> &nbsp; </div><div class="edit-agency-pic p-absolute anim bg-color-red f-color-w snap" data-type="editAgencyPic"> <div class="p-relative t-center" style="  margin-left: -9px;"> <div class="sprite-im Edit-icon inline-block v-align-mid" > &nbsp; </div><div class="inline-block f-sz-12 v-align-mid opensans-regular "> Edit </div></div></div></div><div class="left agency-name-details t-left anim"> <div id="agencyNameValue" class="opensans-regular text-ellipsis  f-sz-17 agency-name t-caps" title="' + sessionStorage.agencyName + '"> ' + sessionStorage.agencyName + ' </div><div id="adminEmailIDValue" class="opensans-regular text-ellipsis  agency-email" title= "' + sessionStorage.userEmailId + '"> ' + sessionStorage.userEmailId + ' </div></div></a> </div></div></div></div><div class="topContainer"></div>';
            }

            return Header;
        }

    }
};
